# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'VectorBuilder' do

  use_frameworks!

  pod 'Swinject', '~> 2.8'
  pod 'SnapKit', '~> 5.6'
  pod 'Then', '~> 3.0'
  
end
